#!/bin/bash

##############################################################################################################
# A simple script to run and set up postgres, memcached, aznrserver and aznwserver docker containers.
#
# Usage:
#   Run with sudo if your user is not part of the docker group, run without otherwise.
#   Enter the names of the containers as arguments to the script in the order that you want them to be set up.
#   If you don't want a container to be set up, just omit it from the arguments.
##############################################################################################################

# create network for containers

alias psql-run='docker exec -it postgres psql -U postgres -c'

docker network create azn

for arg in "$@"
do
    case $arg in

        postgres)

            # remove postgres data directory

            rm -rf /postgres

            # kill and remove containers

            docker rm --force postgres

            # set up postgres

            docker pull postgres

            docker run \
              --detach \
              --restart unless-stopped \
              --network azn \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=615465489156 \
              --name postgres \
              -v /postgres/data:/var/lib/postgresql/data \
              -v /postgres/backup_wal:/backup_wal \
              -v /postgres/basebackup:/basebackup \
              -d postgres

            # wait until database has started

            sleep 20

            # inside postgres container

            psql-run "CREATE USER azn WITH PASSWORD '615465489156';" \
                      "CREATE DATABASE azn;" \
                      "GRANT ALL ON DATABASE azn TO azn;" \
                      "ALTER DATABASE azn OWNER TO azn;"

            psql-run "\c azn"

			# this might be executed manually,
			# as psql will only add the extension for db postgres for some reason

            psql-run "CREATE EXTENSION hstore;"
			psql-run "\q"
			;;

        memcached)

            docker rm --force memcached

            # set up memcached

            docker pull memcached

            docker run \
              --detach \
              --restart unless-stopped \
              --network azn \
              --name memcached \
              -d memcached
			;;
        
        aznrserver)

            # log into github through docker 
            
            echo 'Logging into ghcr.io...'

            read -rp 'Username: ' username

            docker login ghcr.io -u "$username"

            docker rm --force aznrserver

            # set up azn resource server

            docker pull ghcr.io/lokcenter/azn_spring_resourceserver:main

            docker run \
             -d \
             --restart unless-stopped \
             --network azn \
             --name aznrserver \
             -e spring_datasource_username=azn \
             -e spring_datasource_password=615465489156 \
             -e spring_cloud_azure_active-directory_credential_client-id=83dec9cc-0927-4253-afce-11b56a046479 \
             -e spring_cloud_azure_active-directory_credential_client-secret=j~X8Q~IkAAa7hsgdiz1EgKcZxAe-iMz5DHvtsdy6 \
             -e spring_cloud_azure_active-directory_profile_tenant-id=8965f925-d5b9-41f6-8b4c-93acad130ac2 \
             -e spring_mail_host=smtp.office365.com \
             -e spring_mail_port=587 \
             -e spring_mail_username=azn@ausbildung-bbw.de \
             -e spring_mail_password=Lok@123456 \
             -e spring_mail_properties_mail_smtp_auth=true \
             -e spring_mail_properties_mail_smtp_starttls_enable=true \
             -t ghcr.io/lokcenter/azn_spring_resourceserver:main 
			;;

        aznwserver)

            docker rm --force aznwserver

            # set up azn web server

            docker pull ghcr.io/lokcenter/azn_spring_webclient:main

            docker run \
              -d \
              -p 8880:8880 \
              --restart unless-stopped \
              --name aznwserver \
              --network azn \
              -e server_port=8880 \
              -e azure_activedirectory_client-id=83dec9cc-0927-4253-afce-11b56a046479 \
              -e azure_activedirectory_client-secret=j~X8Q~IkAAa7hsgdiz1EgKcZxAe-iMz5DHvtsdy6 \
              -e azure_activedirectory_tenant-id=8965f925-d5b9-41f6-8b4c-93acad130ac2 \
              -t ghcr.io/lokcenter/azn_spring_webclient:main 
			;;
        
        *)

            echo "Unknown argument \"$arg\"" 
			;;

   esac

done
