package com.lokcenter.AZN.selenium;

// Generated by Selenium IDE
import org.junit.*;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

@FixMethodOrder(MethodSorters.JVM)
public class UserTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/test/java/com/lokcenter/AZN/selenium/driver/chromedriver");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.get("http://localhost:8880");
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void login() {
        driver.findElement(By.cssSelector(".btn-absolute")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.elementToBeClickable(By.name("loginfmt")));
        }
        driver.findElement(By.name("loginfmt")).click();
        driver.findElement(By.name("loginfmt")).sendKeys("tomtest@2v40nf.onmicrosoft.com");
        driver.findElement(By.id("idSIButton9")).click();
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
            wait.until(ExpectedConditions.elementToBeClickable(By.name("passwd")));
        }
        driver.findElement(By.name("passwd")).click();
        driver.findElement(By.name("passwd")).sendKeys("SSW,Gr\"V)7Pa(r{qe5!,");
        driver.findElement(By.id("idSIButton9")).click();
        driver.findElement(By.id("idBtn_Back")).click();
        String actualUrl = "http://localhost:8880/dayplan";
        String expectedUrl = driver.getCurrentUrl();
        Assert.assertEquals(expectedUrl,actualUrl);
        String actual = String.valueOf(driver.findElement(By.className("dayPlanInput-container")));
        Boolean actualBool = false;
        if (actual.length() > 0) {actualBool = true;}
        Assert.assertTrue(actualBool);
    }
}
